### ISSUE TITLE
RPi defaults to en-GB locale, but probably should be en-US

### ISSUE THREAD

**Issue by davidflanagan** [mozilla/vaani.raspberrypi#1]
wpa_supplicant.conf includes

  country=GB

Also:

$ echo $LANG
en_GB.UTF-8

I'm assuming all the user testing will be in the US so maybe run raspi-config to change these?

I don't know if the locale matters at all, but getting the wifi country right might be important. (But I don't actually know if there are any differences between US and GB wifi channels.)

**Comment by floatingatoll** [comment]
There are significant differences in 2.4GHz operation, and specifically two
channels are enabled for GB operation that are illegal to operate in the US.
- R.
